version = 1

[[analyzers]]
name = "sql"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"